name: Deploy CRA Admin to Azure Static Web Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, closed ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (use Node 20)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Build app (CI=false) and inject API base
        run: npm run build
        env:
          CI: "false"
          # 你的 api.js 同时兼容这两个变量名，二者都注入更稳
          REACT_APP_API_BASE: ${{ vars.API_BASE_URL }}
          REACT_APP_API_URL:  ${{ vars.API_BASE_URL }}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "build"

